### Get template list
GET http://localhost:8080/templates

### Get template list
DELETE http://localhost:8080/templates/delete/5

### Create template
POST http://localhost:8080/templates/create
Content-Type: application/json

{
  "levelNumber": 5,
  "season": "SUMMER",
  "startTime": 8,
  "endTime": 20,
  "objective": {
    "maxCO2": 2,
    "maxCoins": 2
  },
  "transformers": [
    {
      "maxBatteryCount": 0,
      "congestion": {
        "hasCongestion": false,
        "maxCurrent": 0
      },
      "houses": [
        {
          "hasElectricVehicle": false,
          "hasHeatPump": false,
          "maxSolarPanels": 1,
          "maxBatteries": 1,
          "congestion": {
            "hasCongestion": false,
            "maxCurrent": 0
          }
        }
      ]
    }
  ]
}

### Update template
POST http://localhost:8080/templates/update/102
Content-Type: application/json

{
  "levelNumber": 5,
  "season": "SUMMER",
  "startTime": 7,
  "endTime": 20,
  "objective": {
    "maxCO2": 2,
    "maxCoins": 2
  },
  "transformers": [
    {
      "maxBatteryCount": 0,
      "congestion": {
        "hasCongestion": false,
        "maxCurrent": 0
      },
      "houses": [
        {
          "hasElectricVehicle": false,
          "hasHeatPump": false,
          "maxSolarPanels": 1,
          "maxBatteries": 1,
          "congestion": {
            "hasCongestion": false,
            "maxCurrent": 0
          }
        }
      ]
    }
  ]
}

### Start level 1
GET http://localhost:8080/levels/start/1

### Start level 2
GET http://localhost:8080/levels/start/2

### Update level 1
POST http://localhost:8080/levels/update/1
Content-Type: application/json

{
  "transformers": [
    {
      "id": 1,
      "houses": [
        {
          "id": 1,
          "batteries": 0,
          "solarpanels": 6
        },
        {
          "id": 2,
          "batteries": 0,
          "solarpanels": 8
        }
      ],
      "batteries": 0
    }
  ]
}
